### ISSUE TITLE
getCurrentSeason broken after liga.99damage.de update

### ISSUE THREAD

**Issue by Jasperhino** [NiclasEgeler/99damage#6]
Hi, wollte heute die API mal austesten und hab festgestellt, dass die anscheinend beim update der 99damage Seite kaputt gegangen ist. Habt ihr vor das zu fixen oder bin ich besser dran wenn ich einfach selber scrape?

```
server\node_modules\99damage\lib\99damage.js:381
                        teamstable = $(".section-content")[0].children[1].children[3].children;
                                                                                     ^
TypeError: Cannot read property 'children' of undefined
at Function.<anonymous> (...\server\node_modules\99damage\lib\99damage.js:381:86)
    at step (...\server\node_modules\99damage\lib\99damage.js:52:23)
    at Object.next (...\server\node_modules\99damage\lib\99damage.js:33:53)
    at fulfilled (...\server\node_modules\99damage\lib\99damage.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


```

**Comment by NiclasEgeler** [comment]
Hey,
ja das Update hat die API wohl zerschossen. 
Wir schauen es uns mal an.

**Comment by BenediktBertsch** [comment]
@Jasperhino Hey, leider können wir aktuell diese Funktion nicht debuggen, da wir nicht aktiv in dieser Saison teilnehmen. Gerne kann ich mir das Problem anschauen wenn ich Zugangsdaten zum testen bekomme.

**Comment by Jasperhino** [comment]
Hmm würde meinen Account ungern dafür bereitstellen. Eigentlich müssen doch nur die selectors auf die neue Seite angepasst werden oder? Dann guck ich mal, ob ich das selber fixe und nen PR stelle

**Comment by BenediktBertsch** [comment]
Ja klar. PRs sind immer willkommen. Habe auch eher an einen Zweitaccount oä. gedacht der eurem Team z.B. nur temporär zugeordnet ist.
